setGeneric("exprsToLong", function(x,...) standardGeneric("exprsToLong"))
setGeneric("contrastNames", function(object) standardGeneric("contrastNames"))
setGeneric("designVariables", function(object) standardGeneric("designVariables"))

setGeneric("groups", function(object) standardGeneric("groups"))
setGeneric("dispGroups", function(object) standardGeneric("dispGroups"))
setGeneric("designMatrix", function(object) standardGeneric("designMatrix"))
setGeneric("contrastMatrix", function(object) standardGeneric("contrastMatrix"))
setGeneric("nContrast", function(object) standardGeneric("nContrast"))
setGeneric("contrastSampleIndices", function(object, contrast) standardGeneric("contrastSampleIndices"))
