// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cossimVec
RcppExport SEXP cossimVec(SEXP x, SEXP y, SEXP narm);
RcppExport SEXP _ribiosMath_cossimVec(SEXP xSEXP, SEXP ySEXP, SEXP narmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type narm(narmSEXP);
    rcpp_result_gen = Rcpp::wrap(cossimVec(x, y, narm));
    return rcpp_result_gen;
END_RCPP
}
// empval
RcppExport SEXP empval(SEXP a, SEXP b);
RcppExport SEXP _ribiosMath_empval(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(empval(a, b));
    return rcpp_result_gen;
END_RCPP
}
// colKappa
RcppExport SEXP colKappa(SEXP Xs);
RcppExport SEXP _ribiosMath_colKappa(SEXP XsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Xs(XsSEXP);
    rcpp_result_gen = Rcpp::wrap(colKappa(Xs));
    return rcpp_result_gen;
END_RCPP
}
// colKappaSimp
RcppExport SEXP colKappaSimp(SEXP Xs);
RcppExport SEXP _ribiosMath_colKappaSimp(SEXP XsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Xs(XsSEXP);
    rcpp_result_gen = Rcpp::wrap(colKappaSimp(Xs));
    return rcpp_result_gen;
END_RCPP
}
// randmat
RcppExport SEXP randmat(SEXP x, SEXP n, SEXP N);
RcppExport SEXP _ribiosMath_randmat(SEXP xSEXP, SEXP nSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(randmat(x, n, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ribiosMath_cossimVec", (DL_FUNC) &_ribiosMath_cossimVec, 3},
    {"_ribiosMath_empval", (DL_FUNC) &_ribiosMath_empval, 2},
    {"_ribiosMath_colKappa", (DL_FUNC) &_ribiosMath_colKappa, 1},
    {"_ribiosMath_colKappaSimp", (DL_FUNC) &_ribiosMath_colKappaSimp, 1},
    {"_ribiosMath_randmat", (DL_FUNC) &_ribiosMath_randmat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ribiosMath(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
