# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cossimVec <- function(x, y, narm) {
    .Call('_ribiosMath_cossimVec', PACKAGE = 'ribiosMath', x, y, narm)
}

#' Get empirical p-value
#' 
#' Calculate empirical p-values from real values and simulated values
#' 
#' @param stat A numeric vector of calculated statistic from the actual data
#' @param sim A numeric vector (or matrix) of simulated statistics, e.g. by Monte-Carlo methods.
#' 
#' @details
#' The estimate of the P-value is obtained as \eqn{\hat{p}=(r+1)/(n+1)},
#' where \code{n} is the number of replicate samples that have been
#' simulated and \code{r} is the number of these replicates that produce
#' a test statistic greater than or equal to that calculated for the
#' actual data.
#' 
#' @return A vector of empirical p-values, of the same length as the input
#' 
#' @references
#' \itemize{
#' \item{Davison AC, Hinkley DV (1997) Bootstrap methods and their
#' applications. Cambridge University Press, Cambridge, United Kindom.}
#' \item{North BV, Curtis D, Sham PC (2002) A note on the calculation of
#' empirical p values from Monte Carlo Procedures. Am J Hum Genet. 2002
#' August; 71(2):439--441.}
#' }
#' @author
#' Jitao David Zhang <jitao_david.zhang@roche.com>
#' 
#' @examples
#' set.seed(1995)
#' testStat <- c(-100, -3, -1, 0, 1, 3, 100)
#' testSim <- rnorm(1000)
#' empval(stat=testStat, sim=testSim)
#' @export
empval <- function(stat, sim) {
    .Call('_ribiosMath_empval', PACKAGE = 'ribiosMath', stat, sim)
}

#' Calculate column-wise kappa statistics of a matrix
#'
#' The function returns column-wise kappa statistics of a matrix, using a linear algebra procedure implemented in C++.
#'
#' @param matrix a binary matrix, containing values of either 0 or 1.
#'
#' @return
#' A matrix of size \eqn{n \times n} if the input matrix is of size \eqn{m \times n}.
#'
#' @family kappa functions
#' @seealso \code{\link{rowKappa}} to calculate the statistic of rows
#' 
#' @examples
#' testMat <- cbind(c(1,1,0,0,1,0), c(1,1,0,1,1,0))
#' colKappa(testMat)
#' 
#' @export
colKappa <- function(matrix) {
    .Call('_ribiosMath_colKappa', PACKAGE = 'ribiosMath', matrix)
}

colKappaSimp <- function(Xs) {
    .Call('_ribiosMath_colKappaSimp', PACKAGE = 'ribiosMath', Xs)
}

#' Perform heuristic fuzzy multi-linkage partitioning of DAVID
#' 
#' @examples 
#' testMat <- cbind(c(1,1,0,0,1,0), c(1,1,0,1,1,0), c(1,0,1,1,0,1))
#' testKappaMat <- rowKappa(testMat)
#' davidClustering_cpp(testKappaMat)
#' 
#' @export
davidClustering_cpp <- function(kappaMatrix, kappaThr = 0.35, initialGroupMembership = 3L) {
    .Call('_ribiosMath_davidClustering_cpp', PACKAGE = 'ribiosMath', kappaMatrix, kappaThr, initialGroupMembership)
}

#' Make a random matrix by sampling
#' 
#' Generating a random matrix by sampling a numeric vector with replacement per column.
#' 
#' @param vec A numeric vector to be sampled from
#' @param size Integer, size of sampling, or the row count of the matrix.
#' @param N Integer, number of sampling repeats, or the column count of the matrix.
#' 
#' @details
#' The function generates a matrix of the dimension \eqn{size \times N}. Each column of the matrix is a random sampling of the input vector.
#'   
#' Currently only sampling \emph{with replacement} is supported. 
#' @return A random matrix of the dimension \eqn{size \times N}.
#' @author Jitao David Zhang <jitao_david.zhang@roche.com>
#' 
#' @examples
#' testVec <- 1:10
#' randmat(testVec, size=5L, N=10L)
#'@export
randmat <- function(vec, size, N) {
    .Call('_ribiosMath_randmat', PACKAGE = 'ribiosMath', vec, size, N)
}

