#' Internal function used by readBiokitExpression
#' 
#' @param keys A vector of character strings
#' @param dfList A list of data.frames to be matched
#' @param keyColumn The column of keys in the data.frames of dfList
#' @param valueColumns One or more character strings, column names in the data.frames of dfList
#' 
#' #@importFrom ribiosUtils matchColumn
#' @return A list of matrices, each containing one value column

matchKeyValue <- function(keys, dfList, keyColumn, valueColumns) {
  subdfList <- lapply(dfList, 
                      function(x) matchColumn(keys, x, keyColumn)[, valueColumns])
  resList <- lapply(valueColumns, function(col) {
    res <- do.call(cbind, lapply(subdfList, function(x) x[,col]))
    rownames(res) <- keys
    res[is.na(res)] <- 0
    return(res)
  })
  return(resList)
}

#' Read Biokit Expression files
#' 
#' @param files One or more expression files generated by the Biokit software
#' @param exprsType Which data types should become the exprs element of the resulting ExpressionSet.
#' @param ngsPipelineSampleInfoFile Sample info file used by Roche Bioinformatics NGS pipeline, a headerless TSV file including sample name, sample group, and FASTQ files, one sample per line
#' 
#' \code{readBiokitExpression} calls read_biokit_exprs in ribiosIO to read BioKit expression data, 
#' and combine data from multiple files into one ExpressionSet object
#' 
#' # @importFrom ribiosIO read_biokit_exprs
#' # @importClassesFrom Biobase ExpressionSet AnnotatedDataFrame
#' 
#' @examples 
#' biokitFiles <- system.file("extdata/biokit_expression_files",
#'   sprintf("biokit-output-%d.expression", 1:4),
#'   package="ribiosNGS")
#' biokitEset <- readBiokitExpression(biokitFiles)
readBiokitExpression <- function(files,
                                 exprsType=c("ReadCount_UniqMap", "RPKM_UniqMap",
                                             "ReadCount_MultiMap", "RPKM_MultiMap",
                                             "AllMappingReads"),
                                 ngsPipelineSampleInfoFile=NULL) {
  exprsType <- match.arg(exprsType)
  tbls <- lapply(files, read_biokit_exprs)
  featTbls <- lapply(tbls, function(x) {
    annoCols <- grepl("^Annotation", colnames(x))
    res <- data.frame(Feature=rownames(x),
                      x[,annoCols])
    return(res)
  })
  featTbl <- unique(do.call(rbind, featTbls))
  uniqFeatures <- featTbl$Feature
  rownames(featTbl) <- uniqFeatures
  valueCols  <- c("RPKM_MultiMap","ReadCount_MultiMap",
                  "RPKM_UniqMap","ReadCount_UniqMap",
                  "MultiProp", "AllMappingReads")
  valueNames <- valueCols; valueNames[valueCols == exprsType] <- "exprs"
  valueMats <- matchKeyValue(uniqFeatures, tbls, 0L, valueCols)
  resEnv <- new.env()
  sapply(seq(along=valueCols), function(i) assign(x=valueNames[i], 
                                                  value=valueMats[[i]],
                                                  envir=resEnv))
  res <- new("ExpressionSet",
             assayData=resEnv,
             featureData=new("AnnotatedDataFrame", featTbl))
  sampleNames(res) <- basefilename(files)
  if(!is.null(ngsPipelineSampleInfoFile)) {
    sampleInfo <- read.table(ngsPipelineSampleInfoFile, head=FALSE,
                             col.names=c("SampleName", "SampleGroup", "Fastq1", "Fastq2"))
    sampleInfo <- matchColumn(sampleNames(res), sampleInfo, "SampleName")
    rownames(sampleInfo) <- sampleNames(res)
    pData(res) <- sampleInfo
  }
  return(res)
}

#' Read GCT files from Biokit output directory
#' @param dir Biokit output directory
#' @param anno Annotation type, either \code{refseq} or \code{ensembl} is supported
#' @param type GCT file type, \code{count}, \code{rpkm}, \code{uniqCount} and \code{uniqRpkm} are supported.
#' @return A numeric matrix with the attribute \code{desc} encoding the values in the description column of the GCT format
#' 
#' @examples
#' ##... (TODO: add a mock output directory in testdata)
readBiokitGctFile <- function(dir, 
                              anno=c("refseq", "ensembl"),
                              type=c("count", "rpkm", "uniqCount", "uniqRpkm")) {
  anno <- match.arg(anno)  
  type <- match.arg(type)
  
  annoPath <- switch(anno,
                     "refseq"="gct",
                     "ensembl"="gct-ens")
  
  gctDir <- file.path(dir, annoPath) 
  assertDir(gctDir)
  
  filePattern <- switch(type,
                        "count"=".*_counts.gct",
                        "rpkm"=".*_rpkms.gct",
                        "uniqCount"=".*uniq-counts.gct",
                        "uniqRpkm"=".*uniq-rpkms.gct")
  
  gctFile <- dir(gctDir, pattern=filePattern, full.names=TRUE)
  mat <- read_gct_matrix(gctFile)
  return(mat)
}

#' Read a Biokit output directory into a DGEList object for downstream analysis
#' @param dir Biokit output directory
#' @param anno Annotation type, either \code{refseq} or \code{ensembl} is supported
#' @param type count type, either \code{count} or \code{uniqCount} are supported.
#' @examples
#' ##... (TODO: add a mock output directory in testdata)
readBiokitAsDGEList <- function(dir, 
                                anno=c("refseq", "ensemble"),
                                countType=c("count", "uniqCount")) {
  ## read gct file
  anno <- match.arg(anno)
  countType <- match.arg(countType)
  mat <- readBiokitGctFile(dir, anno=anno, type=countType)
  
  ## read sample annotation
  annotFile <- file.path(dir, "annot", "phenoData.meta")
  if(file.exists(annotFile)) {
    annot <- ribiosIO::readTable(annotFile)
    annot$group <- annot$SampleGroup
  } else {
    warning("No sample annotation was found. A mock annotation is used")
    annot <- data.frame(group=factor(rep("sample", ncol(mat))),
                        row.names=colnames(mat))
  }
  
  ## wish to Roland: feautre annotation
  genes <- data.frame(GeneID=rownames(mat), GeneSymbol=attr(mat, "desc"))
  
  res <- DGEList(counts=mat, samples=annot, genes=genes)
  res$BiokitAnno <- anno
  res$BiokitCountType <- countType
  return(res)
}
